name: Build .net api
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['3.1.x']
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'

      - uses: microsoft/variable-substitution@v1 
        with:
            files: 'appsettings.json'
        env:
            PackageApiUrl: "${{ secrets.PAKKET_URL }}"
            LocationApiUrl: "${{ secrets.LOCATIE_URL }}"
          
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build *.csproj
