name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set image tag environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
         # list of Docker images to use as base name for tags
         images: |
          fipost/ui
         tags: |
           $RELEASE_VERSION
              
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fipost/ui:${{ env.RELEASE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "GATEWAY_URL=${{ secrets.GATEWAY_URL }}"
            "APP_URL=${{ secrets.APP_URL }}"
          
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fipost/ui:${{ env.RELEASE_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "GATEWAY_URL=${{ secrets.GATEWAY_URL }}"
            "APP_URL=${{ secrets.APP_URL }}"
