name: Build and test .NET API
on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['3.1.x']
    name: Dotnet ${{ matrix.dotnet }} build and test
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet build
      - run: dotnet test
